Repository thuongtruong1009/gitbox, pull requests merged in 2021-12, with the labels that each got.

#33 feat: add contributing chart feature
  .gitignore
  README.md
  about.sh
  karma.conf.js
  package-lock.json
  package.json
  src/App.vue
  src/assets/download.png
  src/assets/fork.svg
  src/assets/git.png
  src/assets/github.jpg
  src/assets/logo.png
  src/assets/net.png
  src/components/Accessibilities.vue
  src/components/Main.vue
  src/components/Repositories.vue
  src/components/SideBar.vue
  src/main.js
  src/style/global.css
  vue.config.js
  webpack.config.js
Labels: enhancement, vuejs

#37 fix: add click event for search button
  src/components/Main.vue
Labels: enhancement, good first issue, vuejs

#38 fixes: converting CSS by Boostrap5
  public/assets/download.png
  public/assets/fork.svg
  public/assets/git.png
  public/assets/github.jpg
  public/assets/globe.png
  public/assets/logo.png
  public/assets/net.png
  public/index.html
  src/App.vue
  src/components/Footer.vue
  src/components/Main.vue
  src/components/Repositories.vue
  src/components/SideBar.vue
Labels: vuejs, update

#39 fixes: render teleport layouts
  README.md
  images reference/project.jpg
  images reference/view_demo.jpeg
  public/assets/octocat.png
  public/assets/octocats.svg
  public/postman.svg
  src/App.vue
  src/components/Main.vue
  src/components/Repositories.vue
  src/components/SideBar.vue
  src/data/org.json
  src/data/repos.json
  src/data/started.json
  src/data/user.json
  src/layouts/Followers.vue
  src/layouts/Following.vue
  src/layouts/Gists.vue
  src/layouts/Repositories.vue
  src/layouts/Stars.vue
  vue.config.js
Labels: bug, enhancement, vuejs
